#!/usr/bin/env python3

from hw_device_mgr.mgr_ros_hal.mgr import (
    ROSHALHWDeviceMgr,
    SimROSEtherCATHWDeviceMgr,
)
import sys

if __name__ == "__main__":
    argv = list(sys.argv[1:])  # Knock off executable name
    sim = "--sim" in argv
    if sim:
        mgr = SimROSEtherCATHWDeviceMgr(sim=True)
    else:
        mgr = ROSHALHWDeviceMgr()
    mgr.init(argv)
    if sim:
        mgr.init_sim()
    mgr.init_devices()
    mgr.run()
